apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: illumaria/online_inference:v4
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      readinessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 10
